### ISSUE TITLE
Convert artwork to sensible (jpeg) format?

### ISSUE THREAD

**Issue by AndyLandy** [AndyLandy/MakeMP3#9]
Might be worth auto-converting all album artwork to jpg, and possibly a specified resolution.

**Comment by luxagen** [comment]
Maybe we should make a list of ID3-supported image formats and divide them into "don't transcode" and "transcode" sublists?

**Comment by AndyLandy** [comment]
I think this is beyond the scope of MakeMP3 itself, but some kind of helper script might be in order. ("MakeJPG" perhaps...)

**Comment by AndyLandy** [comment]
I suspect this feature is overkill. It's certainly out-of-scope for MakeMP3, and I doubt the companion MakeJPG is likely to ever see the light of day. Closing this as WONTFIX.
